export const STRINGS = {
  appName: 'Live Chat Palette',
  tabEmoji: 'Emojis',
  tabPreset: 'Presets',
  collapse: 'Collapse Live Chat Palette',
  expand: 'Expand Live Chat Palette',
  openSettings: 'Open settings',
  dismiss: 'Dismiss',
  presetEmptyTitle: 'No message presets yet.',
  presetEmptyHint: 'Add a preset to insert it into the chat with one click.',
  addPreset: '+ Add preset',
  presetTextLabel: 'Preset text',
  presetScopeLabel: 'Scope',
  scopeGlobal: 'All channels',
  scopeChannel: 'This channel only',
  save: 'Save',
  cancel: 'Cancel',
  presetHint: 'Click to insert. Cmd/Ctrl + Click to insert and send.',
  presetHintInstant: 'Instant send is on: clicking a preset inserts and sends it.',
  emojiEmptyTitle: 'No favorite emojis yet.',
  emojiEmptyHint: "Open or refresh YouTube's emoji picker to discover available custom emojis.",
  refreshEmojis: 'Refresh emojis',
  refreshing: 'Refreshing…',
  availableEmojis: 'Available custom emojis',
  noCustomEmojis: 'No custom emojis were found in the emoji picker.',
  favorites: 'Favorites',
  addFavorite: (name: string): string => `Add ${name} to favorites`,
  removeFavorite: (name: string): string => `Remove ${name} from favorites`,
  insertEmoji: (name: string): string => `Insert ${name}`,
  insertPreset: (text: string): string => `Insert preset: ${text}`,
  emojiUnavailable: 'This favorite emoji is not currently available.',
  emojiUnavailableBadge: 'Currently unavailable',
  chatUnsupported: "YouTube's chat input could not be recognized.",
  emojiUnsupported: 'Custom emojis are currently unavailable.',
  channelUnknown: 'Channel information could not be determined. Global presets remain available.',
  channelUnknownEmoji:
    'Channel information could not be determined. Favorite emojis are unavailable.',
  sendFailed: 'The comment could not be sent. Your draft has been kept when possible.',
  insertFailed: 'The text could not be inserted into the chat input.',
  sendLocked: 'Please wait a moment before sending again.',
} as const;
